# Site settings
title:       Deep Learning Math
email:       rong.ou@gmail.com
author:      Rong Ou
description: "A software engineer tries to understand the math behind deep learning."
baseurl:     ""
url:         "http://rongou.github.io"

# Google analytics
google_analytics: UA-63479909-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: rongou

# Social icons
show_social_icons: true
github_username: rongou
stackoverflow_id: 4946958
twitter_username: rongou
google_plus_id: +RongOu
linkedin_username: rongou
angellist_username: rongou
bitcoin_url: https://www.coinbase.com/rongou
paypal_url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2JCB8RGAT9NVW

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this:'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
permalink:    pretty
paginate:     3
sass:
  compressed: true
